### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by techmsi** [gskachkov/tstatompackage#1]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Apps4Dev/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/sidromenos/.atom/packages/coverage-gutter/lib/main.coffee:12:10)
```

**Comment by gskachkov** [comment]
@techmsi Thanks for looking to my package!
Now it is fixed. Please check if it helps/
