### ISSUE TITLE
Atom using a config name of coverage-gutter instead of tstpackage

### ISSUE THREAD

**Issue by enigmak** [gskachkov/tstatompackage#2]
in lib/coverage-view.coffee

14      basePath = atom.config.get('tstpackage.basePath')
...
22    pathToLCOV = atom.config.get('tstpackage.pathToLCOV')

I had to change tstpackage to coverage-gutter in order to get the package to work.

**Comment by gskachkov** [comment]
@enigmak  Thanks for the interesting in this package.
I've not updated ATOM for several months, and missed last broken changes. 
I've fixed and update package. Please notify if it doesn't  help

**Comment by gskachkov** [comment]
@enigmak I assume that new version is fixed your issue.

**Comment by enigmak** [comment]
Yes it fixed the issue thanks.
