### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by call-a3** [gskachkov/tstatompackage#3]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.

```
Object.Object.defineProperty.get (C:\Users\Me\AppData\Local\atom\app-0.192.0\resources\app\exports\atom.js:66:11)
Object.<anonymous> (C:\Users\Me\.atom\packages\coverage-gutter\lib\coverage-view.coffee:4:1)
```

**Comment by gskachkov** [comment]
Great! Thanks for PR, I'll check the on my Atom and release new version soon. Thanks for the contribution!

**Comment by call-a3** [comment]
Np, happy to help
