### ISSUE TITLE
Deprecated selector in `coverage-gutter/styles/tstpackage.less`

### ISSUE THREAD

**Issue by xdumaine** [gskachkov/tstatompackage#9]
In `coverage-gutter/styles/tstpackage.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter div.covered` => `atom-text-editor.editor .gutter div.covered`

* `atom-text-editor::shadow .gutter div.not-covered` => `atom-text-editor.editor .gutter div.not-covered`

* `atom-text-editor::shadow .gutter div.partly-covered` => `atom-text-editor.editor .gutter div.partly-covered`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by magestican** [comment]
any updates on this ?

**Comment by gskachkov** [comment]
Sorry, Gents. I do not work on this anymore :-( Currently  I'm contributing only to the Webkit/JSC.
